version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.9.1
workflows:
  build-and-push-to-ecr:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          dockerfile: ./Dockerfile
          repo: kotlin-base-image
          tag: '${CIRCLE_SHA1}'
